format = """
[$os](fg:nord7 bg:nord0)[\uE0B0](fg:nord0 bg:nord1)\
[ $directory ](fg:nord1 bg:nord1)[\uE0B0](fg:nord1 bg:nord2)\
$git_branch[\uE0B0](fg:nord2 bg:nord3)\
$git_status[\uE0B0](fg:nord3 bg:nord7)\
$time[\uE0B0](fg:nord7 bg:none)\
$all$character """

add_newline = true

palette = 'nord'

[palettes.nord]
# Polar Night
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
# Snow Storm
nord4 = '#D8DEE9'
nord5 = '#E5E9F0'
nord6 = '#ECEFF4'
# Frost
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
nord9 = '#81A1C1'
nord10 = '#5E81AC'
# Aurora
nord11 = '#BF616A'
nord12 = '#D08770'
nord13 = '#EBCB8B'
nord14 = '#A3BE8C'
nord15 = '#B48EAD'

[directory]
style = "bg:nord1 fg:nord7"
truncation_length = 0

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:nord2 fg:nord14"

[git_status]
#format = "[ $all_status$ahead_behind ]($style)"
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind$stashed)]($style)"

style = "bg:nord3 fg:nord11"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:nord7 fg:nord5"

[os]
disabled = false
format = "[ $symbol]($style)"
style = "fg:nord7 bg:nord0"

[os.symbols]
Windows = " "
Macos = " "
Debian = " "
Ubuntu = " "
